<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Oops 404 | CTT fw</title>
	<style type="text/css">
		body {
			font-family: 'roboto', cursive;
		}

		body {
			background: #eaeaea;
		}

		.wrap {
			margin: 0 auto;
			width: 1000px;
		}

		.logo {
			text-align: center;
			margin-top: 200px;
		}

		.logo img {
			width: 350px;
		}

		.logo p {
			color: #272727;
			font-size: 40px;
			margin-top: 1px;
		}

		.logo p span {
			color: lightgreen;
		}

		.sub a {
			color: #fff;
			background: #272727;
			text-decoration: none;
			padding: 10px 20px;
			font-size: 13px;
			font-family: arial, serif;
			font-weight: bold;
			-webkit-border-radius: .5em;
			-moz-border-radius: .5em;
			-border-radius: .5em;
		}

		.footer {
			color: black;
			position: absolute;
			right: 10px;
			bottom: 10px;
		}

		.footer a {
			color: rgb(114, 173, 38);
		}
	</style>
</head>
<body>
	<!---728x90--->
	<div class="wrap">
		<div class="logo">
			<p>OOPS! - Could not Find it</p>
			<img src="./Oops 404 for Website Template for free _ Home __ w3layouts_files/404-1.png">
		</div>
	</div>
	<!---728x90--->

	<div class="footer">
		© 2012 Oops 404 . All Rights Reserved | Design by<a href="http://w3layouts.com/">W3layouts</a>
	</div>
</body>
</html>
